DROP TABLE Offered_Item;

CREATE TABLE Offered_Item(
  user_id INT REFERENCES users ON DELETE RESTRICT,
  product_id INT REFERENCES r_product ON DELETE RESTRICT,
  status_id INT REFERENCES r_status ON DELETE RESTRICT,
  Quantity INT,
  Price_paid MONEY,
  Est_birthdate DATE,
  Registration_number INT,
  RFID_tag INT,
  Breed TEXT,
  Single_brand BOOLEAN,
  Starting_date_of_feed DATE,
  Type_of_feed TEXT,
  Est_completion_date DATE,
  Starting_weight NUMERIC,
  Est_finished_weight NUMERIC,
  Hanging_weight NUMERIC,
  Est_price_to_be_paid MONEY,
  Date_planted DATE,
  Seed_type TEXT,
  Heirloom BOOLEAN,
  GMO BOOLEAN,
  Fertilizer_type_used TEXT,
  Pesticide_type_used TEXT,
  Estimated_qty_planted NUMERIC,
  Estimated_finished_qty NUMERIC,
  Qty_accepted_for_listing NUMERIC,
  Qty_accepted_at_delivery NUMERIC,
  Chargebacks MONEY,
  Delivered_date DATE,
  Delivered_to TEXT
);
